export const library = [
  {
    id: "1",
    title: "To Kill a Mockingbird",
    description:
      "A novel about the serious issues of rape and racial inequality.",
    authors: "Harper Lee",
    favorite: true,
    fileCover: "mockingbird_cover.jpg",
    fileName: "to_kill_a_mockingbird.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "2",
    title: "1984",
    description:
      "A dystopian novel that delves into the dangers of totalitarianism.",
    authors: "George Orwell",
    favorite: true,
    fileCover: "1984_cover.jpg",
    fileName: "1984.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "3",
    title: "The Great Gatsby",
    description: "A critique of the American Dream set in the Jazz Age.",
    authors: "F. Scott Fitzgerald",
    favorite: true,
    fileCover: "great_gatsby_cover.jpg",
    fileName: "the_great_gatsby.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "4",
    title: "Pride and Prejudice",
    description:
      "A romantic novel that also critiques the British landed gentry.",
    authors: "Jane Austen",
    favorite: true,
    fileCover: "pride_and_prejudice_cover.jpg",
    fileName: "pride_and_prejudice.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "5",
    title: "The Catcher in the Rye",
    description:
      "A novel that explores themes of teenage angst and alienation.",
    authors: "J.D. Salinger",
    favorite: true,
    fileCover: "catcher_in_the_rye_cover.jpg",
    fileName: "the_catcher_in_the_rye.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "6",
    title: "Brave New World",
    description:
      "A novel that explores a future dystopian society shaped by technology.",
    authors: "Aldous Huxley",
    favorite: true,
    fileCover: "brave_new_world_cover.jpg",
    fileName: "brave_new_world.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "7",
    title: "Moby Dick",
    description: "An epic tale of the hunt for a giant white whale.",
    authors: "Herman Melville",
    favorite: false,
    fileCover: "moby_dick_cover.jpg",
    fileName: "moby_dick.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "8",
    title: "War and Peace",
    description:
      "A historical novel that interweaves the lives of several families during the Napoleonic Wars.",
    authors: "Leo Tolstoy",
    favorite: true,
    fileCover: "war_and_peace_cover.jpg",
    fileName: "war_and_peace.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "9",
    title: "The Lord of the Rings",
    description:
      "An epic high-fantasy novel about the struggle to destroy a powerful ring.",
    authors: "J.R.R. Tolkien",
    favorite: false,
    fileCover: "lotr_cover.jpg",
    fileName: "the_lord_of_the_rings.pdf",
    fileBook: "1740676189429-images.png",
  },
  {
    id: "10",
    title: "The Alchemist",
    description:
      "A philosophical book that deals with the journey of self-discovery.",
    authors: "Paolo Coelio",
    favorite: true,
    fileCover: "alchemist_cover.jpg",
    fileName: "the_alchemist.pdf",
    fileBook: "1740676189429-images.png",
  },
];
